import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {once} from "node:events";
import {access, mkdir, mkdtemp, readFile, rm, writeFile} from "node:fs/promises";
import test from "node:test";
import {tmpdir} from "node:os";
import path from "node:path";
import {createApp} from "../app.js";

const chromeCandidates = [
    process.env.CHROME_BIN,
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
].filter(Boolean);
const authenticatedContext = Object.freeze({
    accountId: "account-1",
    studyId: "study-1",
    participantId: 12,
    participantKey: "participant-a",
});

class HomePool {
    async query(sql) {
        throw new Error(`Unexpected pool query: ${sql}`);
    }
}

const browserHomeProbe = `
const visible = element => {
    const style = getComputedStyle(element);
    return style.display !== "none" && style.visibility !== "hidden" && element.getClientRects().length > 0;
};
const links = selector => [...document.querySelectorAll(selector)].map(link => link.getAttribute("href"));
const box = element => {
    if (!element) return null;
    const {top, left, width, height} = element.getBoundingClientRect();
    return {top: Math.round(top), left: Math.round(left), width: Math.round(width), height: Math.round(height)};
};
const center = element => {
    if (!element) return null;
    const {top, left, width, height} = element.getBoundingClientRect();
    return {x: left + width / 2, y: top + height / 2};
};
const anonymousCopy = document.querySelector("main p.lead")?.textContent.trim() || "";
const progressPhrase = [...document.querySelectorAll("main *")]
    .find(element => element.textContent.trim() === "track your progress." && visible(element));
const result = {
    viewportWidth: window.innerWidth,
    viewportHeight: window.innerHeight,
    stylesReady: getComputedStyle(document.body).display === "flex",
    hasHorizontalOverflow: document.documentElement.scrollWidth > window.innerWidth,
    anonymous: {
        welcomeVisible: [...document.querySelectorAll("main")]
            .some(main => /welcome/i.test(main.textContent) && visible(main)),
        welcomeCenter: center(document.querySelector("main section[aria-labelledby='welcome-title']")),
        loginVisible: [...document.querySelectorAll('a[href="/login"]')].some(visible),
        loginActionCount: links('a[href="/login"]').length,
        canonicalCopyVisible: anonymousCopy === "Labeling is a research study that classifies reasons for rework in pull requests generated by AI agents. Your work is private to you. Log in to begin reviewing PR cards and track your progress.",
        progressPhraseNoWrap: progressPhrase?.classList.contains("text-nowrap") === true,
        headerCount: document.querySelectorAll("header").length,
        privateNavigationLinks: links('header a[href="/queue"], header a[href="/progress"]'),
        privateActionLinks: links('main a[href="/queue"], main a[href="/progress"]'),
    },
    authenticated: {
        headerCount: document.querySelectorAll("header").length,
        headerBox: box(document.querySelector("header")),
        brandRowBox: box(document.querySelector("main > .container > .row:first-child")),
        cardGridBox: box(document.querySelector("main > .container > .row.row-cols-1")),
        identityEmitted: [...document.querySelectorAll("header *")]
            .some(element => element.textContent.trim() === "participant-a"),
        privateNavigationLinks: links('header a[href="/queue"], header a[href="/progress"]'),
        privateActionLinks: links('main a[href="/queue"], main a[href="/progress"]'),
        queueActionLinks: links('main a[href="/queue"]'),
        actionCardCount: document.querySelectorAll("main .card").length,
        loginLinks: links('a[href="/login"]'),
    },
};
setTimeout(() => {
    const output = document.createElement("output");
    output.id = "home-login-probe";
    output.textContent = JSON.stringify(result);
    document.body.append(output);
}, 50);
`;

const createFixtureSessionMiddleware = sessionContext => (req, res, next) => {
    req.sessionContext = sessionContext;
    res.locals.sessionContext = sessionContext;
    res.locals.csrfToken = sessionContext ? "fixture-csrf-token" : null;
    next();
};

const browserHomeProbeMiddleware = (req, res, next) => {
    if (req.path === "/browser-home-probe.js") {
        res.type("application/javascript").send(browserHomeProbe);
        return;
    }
    const render = res.render.bind(res);
    res.render = (view, options) => render(view, options, (error, html) => {
        if (error) return next(error);
        return res.send(html.replace("</body>", "<script src=\"/browser-home-probe.js\"></script></body>"));
    });
    next();
};

const startServer = async sessionContext => {
    const app = await createApp({
        pool: new HomePool(),
        sessionMiddleware: createFixtureSessionMiddleware(sessionContext),
        middleware: [browserHomeProbeMiddleware],
    });
    const server = app.listen(0);
    await once(server, "listening");
    return server;
};

const closeServer = server => new Promise((resolve, reject) => {
    server.close(error => error ? reject(error) : resolve());
    server.closeAllConnections();
});

const findChrome = async () => {
    for (const candidate of chromeCandidates) {
        try {
            await access(candidate);
            return candidate;
        } catch (_error) {
            continue;
        }
    }
    throw new Error("A Chrome or Chromium executable is required; set CHROME_BIN to run the browser regression");
};

const delay = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));

const withTimeout = (promise, timeoutMilliseconds, message) => new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(message)), timeoutMilliseconds);
    promise.then(
        value => {
            clearTimeout(timer);
            resolve(value);
        },
        error => {
            clearTimeout(timer);
            reject(error);
        },
    );
});

class DevToolsConnection {
    constructor(socket) {
        this.socket = socket;
        this.nextRequestId = 1;
        this.pending = new Map();
        this.waiters = [];
        socket.addEventListener("message", event => this.handleMessage(JSON.parse(event.data)));
        socket.addEventListener("close", () => this.handleClose());
    }

    handleClose() {
        const error = new Error("Chrome DevTools connection closed");
        for (const pending of this.pending.values()) {
            clearTimeout(pending.timer);
            pending.reject(error);
        }
        this.pending.clear();
        for (const waiter of this.waiters) {
            clearTimeout(waiter.timer);
            waiter.reject(error);
        }
        this.waiters = [];
    }

    handleMessage(message) {
        if (message.id !== undefined) {
            const pending = this.pending.get(message.id);
            if (!pending) return;
            this.pending.delete(message.id);
            clearTimeout(pending.timer);
            if (message.error) pending.reject(new Error(`${pending.method} failed: ${message.error.message}`));
            else pending.resolve(message.result);
            return;
        }
        this.waiters = this.waiters.filter(waiter => {
            if (waiter.method !== message.method || (waiter.sessionId && waiter.sessionId !== message.sessionId)) return true;
            clearTimeout(waiter.timer);
            waiter.resolve(message.params);
            return false;
        });
    }

    send(method, params = {}, sessionId, timeoutMilliseconds = 15000) {
        const id = this.nextRequestId++;
        const payload = sessionId ? {id, method, params, sessionId} : {id, method, params};
        this.socket.send(JSON.stringify(payload));
        return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
                this.pending.delete(id);
                reject(new Error(`${method} timed out after ${timeoutMilliseconds}ms`));
            }, timeoutMilliseconds);
            this.pending.set(id, {resolve, reject, method, timer});
        });
    }

    waitFor(method, sessionId, timeoutMilliseconds = 15000) {
        return new Promise((resolve, reject) => {
            const waiter = {method, sessionId, resolve, reject};
            waiter.timer = setTimeout(() => {
                this.waiters = this.waiters.filter(entry => entry !== waiter);
                reject(new Error(`Timed out waiting for ${method}`));
            }, timeoutMilliseconds);
            this.waiters.push(waiter);
        });
    }

    close() {
        this.socket.close();
    }
}

const readDevToolsActivePort = async file => {
    for (let attempt = 0; attempt < 200; attempt += 1) {
        try {
            return await readFile(file, "utf8");
        } catch (_error) {
            await delay(50);
        }
    }
    throw new Error("Chrome did not expose its DevTools port");
};

const waitForProcessExit = (child, timeoutMilliseconds) => new Promise(resolve => {
    const settle = () => {
        clearTimeout(timer);
        resolve();
    };
    const timer = setTimeout(settle, timeoutMilliseconds);
    child.once("exit", settle);
    if (child.exitCode !== null || child.signalCode !== null) settle();
});

const signalProcessTree = (child, signal) => {
    try {
        process.kill(-child.pid, signal);
    } catch (_error) {
        try {
            child.kill(signal);
        } catch (_error2) {
            // The browser process group is already gone.
        }
    }
};

const stopBrowserProcess = async child => {
    signalProcessTree(child, "SIGTERM");
    await waitForProcessExit(child, 2000);
    signalProcessTree(child, "SIGKILL");
    await waitForProcessExit(child, 5000);
};

const waitForSocketOpen = (socket, timeoutMilliseconds = 10000) => withTimeout(
    once(socket, "open"),
    timeoutMilliseconds,
    "Timed out opening the Chrome DevTools connection",
);

const waitForSocketClose = (socket, timeoutMilliseconds) => new Promise(resolve => {
    if (socket.readyState === WebSocket.CLOSED) {
        resolve();
        return;
    }
    const timer = setTimeout(resolve, timeoutMilliseconds);
    socket.addEventListener("close", () => {
        clearTimeout(timer);
        resolve();
    }, {once: true});
});

const removeProfileDirectory = directory => rm(directory, {recursive: true, force: true, maxRetries: 5, retryDelay: 100});

const launchBrowser = async chrome => {
    const userDataDirectory = await mkdtemp(path.join(tmpdir(), "labeler-home-chrome-"));
    const child = spawn(chrome, [
        "--headless=new",
        "--disable-background-networking",
        "--disable-default-apps",
        "--disable-extensions",
        // Playwright/Puppeteer parity: hidden scrollbars keep the CSS viewport exactly the requested width.
        "--hide-scrollbars",
        "--no-first-run",
        "--remote-allow-origins=*",
        "--remote-debugging-port=0",
        `--user-data-dir=${userDataDirectory}`,
        "about:blank",
    ], {detached: true, stdio: "ignore"});

    let socket;
    let connection;
    try {
        const activePort = await readDevToolsActivePort(path.join(userDataDirectory, "DevToolsActivePort"));
        const [port, websocketPath] = activePort.trim().split("\n");
        socket = new WebSocket(`ws://127.0.0.1:${port}${websocketPath}`);
        await waitForSocketOpen(socket);
        connection = new DevToolsConnection(socket);
        return {
            connection,
            close: async () => {
                await stopBrowserProcess(child);
                connection.close();
                await waitForSocketClose(socket, 2000);
                await removeProfileDirectory(userDataDirectory);
            },
        };
    } catch (error) {
        if (connection) connection.close();
        if (socket) {
            socket.close();
            await waitForSocketClose(socket, 2000);
        }
        signalProcessTree(child, "SIGKILL");
        await waitForProcessExit(child, 5000);
        await removeProfileDirectory(userDataDirectory);
        throw error;
    }
};

const readHomeProbeOnce = async (browser, url, {width, height}) => {
    const {connection} = browser;
    const {targetId} = await connection.send("Target.createTarget", {url: "about:blank"});
    const {sessionId} = await connection.send("Target.attachToTarget", {targetId, flatten: true});

    try {
        await connection.send("Emulation.setDeviceMetricsOverride", {
            width,
            height,
            deviceScaleFactor: 1,
            mobile: false,
        }, sessionId);
        await connection.send("Page.enable", {}, sessionId);
        const loaded = connection.waitFor("Page.loadEventFired", sessionId);
        await connection.send("Page.navigate", {url}, sessionId);
        await loaded;

        for (let attempt = 0; attempt < 100; attempt += 1) {
            const {result} = await connection.send("Runtime.evaluate", {
                expression: "document.getElementById('home-login-probe')?.textContent ?? null",
                returnByValue: true,
            }, sessionId);
            if (result.value) return JSON.parse(result.value);
            await delay(50);
        }
        throw new Error("The browser Home probe did not report rendered page state");
    } finally {
        try {
            await connection.send("Target.closeTarget", {targetId});
        } catch (_error) {
            // Browser teardown closes the target as well.
        }
    }
};

const homeProbeAttempts = 3;
const homeProbeRetryDelayMilliseconds = 250;

// A transient CDN failure renders the page unstyled, which is an environment failure rather than a layout regression.
const readHomeProbe = async (browser, url, {width, height}) => {
    let layout = await readHomeProbeOnce(browser, url, {width, height});
    for (let attempt = 1; attempt < homeProbeAttempts && !layout.stylesReady; attempt += 1) {
        await delay(homeProbeRetryDelayMilliseconds);
        layout = await readHomeProbeOnce(browser, url, {width, height});
    }
    return layout;
};

const viewportWidths = [375, 768, 1280];
const viewportHeight = 800;
const welcomeCenterTolerancePx = 2;

const authenticatedGeometry = layout => ({
    header: layout.authenticated.headerBox,
    brandRow: layout.authenticated.brandRowBox,
    cardGrid: layout.authenticated.cardGridBox,
});

const assertAuthenticatedGeometryUnchanged = (geometry, baseline, viewport) => {
    for (const [element, rectangle] of Object.entries(geometry)) {
        assert.deepEqual(
            rectangle,
            baseline[element],
            `${viewport}px authenticated ${element} geometry must match the recorded baseline with 0px tolerance`,
        );
    }
};

const persistLayoutSnapshot = async snapshot => {
    const snapshotPath = process.env.HOME_LAYOUT_SNAPSHOT_FILE;
    if (!snapshotPath) return;

    try {
        const baseline = JSON.parse(await readFile(snapshotPath, "utf8"));
        for (const [viewport, geometry] of Object.entries(snapshot)) {
            assertAuthenticatedGeometryUnchanged(geometry, baseline[viewport] ?? {}, viewport);
        }
        return;
    } catch (error) {
        if (error?.code !== "ENOENT") throw error;
    }

    await mkdir(path.dirname(snapshotPath), {recursive: true});
    await writeFile(snapshotPath, `${JSON.stringify(snapshot, null, 2)}\n`);
};

const assertNoHorizontalOverflow = ({layout, viewport}) => {
    assert.equal(layout.hasHorizontalOverflow, false, `Home must not overflow horizontally at ${viewport}px`);
};

test("Given an anonymous server session When Chromium renders Home Then only the welcome and Login entry point are emitted", async () => {
    const chrome = await findChrome();
    const server = await startServer(null);
    const url = `http://127.0.0.1:${server.address().port}/`;
    const browser = await launchBrowser(chrome);

    try {
        for (const viewport of viewportWidths) {
            const layout = await readHomeProbe(browser, url, {width: viewport, height: viewportHeight});

            assert.equal(layout.viewportWidth, viewport, `${viewport}px anonymous Home must render in a real CSS viewport`);
            assert.equal(layout.viewportHeight, viewportHeight, `${viewport}px anonymous Home must render in a real ${viewportHeight}px tall CSS viewport`);
            assert.equal(layout.anonymous.headerCount, 0, `${viewport}px anonymous Home must not emit a header`);
            assert.deepEqual(layout.anonymous.privateNavigationLinks, [], `${viewport}px anonymous Home must not emit private navigation`);
            assert.deepEqual(layout.anonymous.privateActionLinks, [], `${viewport}px anonymous Home must not emit private action cards`);
            assert.equal(layout.anonymous.welcomeVisible, true, `${viewport}px anonymous Home must show a welcome`);
            assert.equal(layout.anonymous.loginVisible, true, `${viewport}px anonymous Home must show Login`);
            assert.equal(layout.anonymous.loginActionCount, 1, `${viewport}px anonymous Home must emit exactly one Login action`);
            assert.equal(layout.anonymous.canonicalCopyVisible, true, `${viewport}px anonymous Home must emit the approved canonical copy`);
            assert.equal(layout.anonymous.progressPhraseNoWrap, true, `${viewport}px anonymous Home must keep "track your progress." together`);
            const welcomeCenter = layout.anonymous.welcomeCenter;
            if (!welcomeCenter) {
                assert.fail(`${viewport}px anonymous Home must expose a measurable welcome area`);
            }
            assert.ok(
                Math.abs(welcomeCenter.x - layout.viewportWidth / 2) <= welcomeCenterTolerancePx,
                `${viewport}px anonymous welcome center x=${welcomeCenter.x.toFixed(2)} must be within ${welcomeCenterTolerancePx}px of ${layout.viewportWidth / 2}`,
            );
            assert.ok(
                Math.abs(welcomeCenter.y - layout.viewportHeight / 2) <= welcomeCenterTolerancePx,
                `${viewport}px anonymous welcome center y=${welcomeCenter.y.toFixed(2)} must be within ${welcomeCenterTolerancePx}px of ${layout.viewportHeight / 2}`,
            );
            assertNoHorizontalOverflow({layout, viewport});
        }
    } finally {
        try {
            await browser.close();
        } finally {
            await closeServer(server);
        }
    }
});

test("Given an authenticated server session When Chromium renders Home Then identity and private actions are emitted without Login", async () => {
    const chrome = await findChrome();
    const server = await startServer(authenticatedContext);
    const url = `http://127.0.0.1:${server.address().port}/`;
    const browser = await launchBrowser(chrome);
    const geometrySnapshot = {};

    try {
        for (const viewport of viewportWidths) {
            const layout = await readHomeProbe(browser, url, {width: viewport, height: viewportHeight});

            assert.equal(layout.viewportWidth, viewport, `${viewport}px authenticated Home must render in a real CSS viewport`);
            assert.equal(layout.viewportHeight, viewportHeight, `${viewport}px authenticated Home must render in a real ${viewportHeight}px tall CSS viewport`);
            assert.equal(layout.authenticated.headerCount, 1, `${viewport}px authenticated Home must emit its header`);
            assert.equal(layout.authenticated.identityEmitted, true, `${viewport}px authenticated Home must emit participant-a`);
            assert.deepEqual(layout.authenticated.privateNavigationLinks, ["/queue", "/progress"], `${viewport}px authenticated Home must emit private navigation`);
            assert.deepEqual(layout.authenticated.privateActionLinks, ["/queue", "/progress"], `${viewport}px authenticated Home must emit private action cards`);
            assert.deepEqual(layout.authenticated.queueActionLinks, ["/queue"], `${viewport}px authenticated Home must emit exactly one queue action link inside main`);
            assert.equal(layout.authenticated.actionCardCount, 2, `${viewport}px authenticated Home must emit exactly two action cards inside main`);
            assert.deepEqual(layout.authenticated.loginLinks, [], `${viewport}px authenticated Home must not emit Login`);
            assertNoHorizontalOverflow({layout, viewport});
            geometrySnapshot[String(viewport)] = authenticatedGeometry(layout);
        }
        await persistLayoutSnapshot(geometrySnapshot);
    } finally {
        try {
            await browser.close();
        } finally {
            await closeServer(server);
        }
    }
});
