BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "reviewer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "labeler_migration" (
  "migration_id" TEXT PRIMARY KEY,
  "applied_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "pr_cards" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "source_card_id" TEXT UNIQUE NOT NULL,
  "source_pr_id" TEXT,
  "repository" TEXT,
  "pr_number" INTEGER,
  "title" TEXT NOT NULL,
  "body" TEXT,
  "author" TEXT,
  "language" TEXT,
  "state" TEXT,
  "merged" BOOLEAN,
  "html_url" TEXT,
  "created_at_source" TEXT,
  "closed_at_source" TEXT,
  "merged_at_source" TEXT,
  "summary" JSONB NOT NULL DEFAULT '{}'::JSONB,
  "evidence" JSONB NOT NULL DEFAULT '{}'::JSONB,
  "raw_payload" JSONB NOT NULL,
  "source_type" TEXT NOT NULL DEFAULT 'CSV',
  "source_checksum" TEXT,
  "content_checksum" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE ("id", "source_card_id")
);

CREATE TABLE IF NOT EXISTS "participant_category" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "participant_id" INTEGER NOT NULL,
  "raw_name" TEXT NOT NULL,
  "normalized_name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE ("participant_id", "normalized_name"),
  UNIQUE ("id", "participant_id"),
  FOREIGN KEY ("participant_id") REFERENCES "reviewer" ("id")
);

CREATE TABLE IF NOT EXISTS "pr_classification" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "pr_card_id" UUID NOT NULL REFERENCES "pr_cards" ("id"),
  "participant_id" INTEGER NOT NULL REFERENCES "reviewer" ("id"),
  "category_id" UUID NOT NULL,
  "remarks" TEXT,
  "classified_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE ("pr_card_id", "participant_id"),
  FOREIGN KEY ("category_id", "participant_id")
    REFERENCES "participant_category" ("id", "participant_id")
);

ALTER TABLE "pr_cards"
  ADD COLUMN IF NOT EXISTS "content_checksum" TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'pr_cards_id_source_card_id_key'
      AND conrelid = 'pr_cards'::regclass
  ) THEN
    ALTER TABLE "pr_cards"
      ADD CONSTRAINT "pr_cards_id_source_card_id_key"
      UNIQUE ("id", "source_card_id");
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "study" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "study_key" TEXT UNIQUE NOT NULL,
  "config" JSONB NOT NULL,
  "source_checksum" TEXT NOT NULL,
  "expected_card_count" INTEGER NOT NULL CHECK ("expected_card_count" = 300),
  "bootstrap_state" TEXT NOT NULL DEFAULT 'PENDING'
    CHECK ("bootstrap_state" IN ('PENDING', 'READY')),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "study_participant" (
  "study_id" UUID NOT NULL REFERENCES "study" ("id"),
  "reviewer_id" INTEGER NOT NULL REFERENCES "reviewer" ("id"),
  "participant_key" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL CHECK ("ordinal" >= 0),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("study_id", "reviewer_id"),
  UNIQUE ("study_id", "participant_key"),
  UNIQUE ("study_id", "ordinal")
);

CREATE TABLE IF NOT EXISTS "study_card" (
  "study_id" UUID NOT NULL REFERENCES "study" ("id"),
  "pr_card_id" UUID NOT NULL,
  "source_card_id" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL CHECK ("ordinal" >= 0),
  "source_checksum" TEXT NOT NULL,
  PRIMARY KEY ("study_id", "pr_card_id"),
  UNIQUE ("study_id", "source_card_id"),
  UNIQUE ("study_id", "ordinal"),
  FOREIGN KEY ("pr_card_id", "source_card_id")
    REFERENCES "pr_cards" ("id", "source_card_id")
);

CREATE INDEX IF NOT EXISTS "study_participant_reviewer_idx"
  ON "study_participant" ("reviewer_id");

CREATE INDEX IF NOT EXISTS "study_card_pr_card_idx"
  ON "study_card" ("pr_card_id");

CREATE INDEX IF NOT EXISTS "pr_cards_repository_pr_number_idx"
  ON "pr_cards" ("repository", "pr_number");

CREATE INDEX IF NOT EXISTS "pr_classification_participant_updated_idx"
  ON "pr_classification" ("participant_id", "updated_at");

CREATE UNIQUE INDEX IF NOT EXISTS "pr_classification_card_participant_uidx"
  ON "pr_classification" ("pr_card_id", "participant_id");

INSERT INTO "labeler_migration" ("migration_id")
VALUES ('001_study_foundation')
ON CONFLICT ("migration_id") DO NOTHING;

COMMIT;
